### PR TITLE
NEXT

### LINKED ISSUE #61: Integrate Next Generation Onion Services
https://blog.torproject.org/tor-0321-alpha-released-support-next-gen-onion-services-and-kist-scheduler

### LINKED ISSUE #73: GUI MVP Features
- [ ] Error UI
- [ ] Transfer UI
- [ ] Reputation UI (quicklook)
- [ ] Pagination

### LINKED ISSUE #74: GUI improvements (round 2)
- [ ] Settings UI
- [ ] Search UI
- [ ] Reputation (expanded view) [computed and atomic data, HD sharing interface]
- [ ] Drag-and-drop uploads
- [ ] State management improvements [connection-swapping, Array-handling clean-up, commit method cleanup.]
- [ ] CSS [animations, color tweaks, responsiveness]

### LINKED ISSUE #85: Tray Icon doesn't appear on Ubuntu 16.04
Hi,

### Package Version

Replace the value below using the output from `orcd --version`.

```
orc      9.0.4 (current HEAD)
protocol 3.1.0
```

Replace the value below using the output from `node --version`.

```
v8.7.0
```

### Expected Behavior

When closing the ORC window a Tray Icon should appear.

### Actual Behavior

Tray Icon does not appear when closing ORC window.

### Steps to Reproduce

1. Make sure libappindicator1 is installed (Needed on Ubuntu, other Apps like Discord or LBRY have it as dependency)
2. git clone
3. npm install
4. npm link
5. orc
6. Close ORC Window

### Note

When creating a fresh project with `electron-forge init` (v4.1.2) and copy over only the Tray logic from the orc  index.js to the forge project index.js (including the .png), it does work. The [Tray Documentation](https://github.com/electron/electron/blob/master/docs/api/tray.md) states that `App indicator will only be shown when it has a context menu.` - tho it didn't make a difference when testing. Putting a context menu into ORC didn't make the Tray Icon appear and not putting Context Menu Code into the forge project still showed the Tray Icon.

Best regards

### LINKED ISSUE #97: More aggressive redundancy strategy
### Package Version

Replace the value below using the output from `orc --version`.

```
orc      9.1.0
protocol 3.1.0
```

Replace the value below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

Shards should not rely solely on erasure codes, but also leverage the `MIRROR` protocol to provide additional redundancy.

### Actual Behavior

Objects are not mirrored and rely solely on parity shards with erasure codes for recovery.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload an object
2. Take your node offline for some days
3. Some objects may have decayed beyond recovery because we weren't online to catch the decay early enough to rebuild and redistribute

### LINKED ISSUE #99: Bootstrap nodes become inaccessible as hidden services after undetermined amount of time
### Package Version

Replace the value below using the output from `orc --version`.

```
orc      9.1.0
protocol 4.0.0
```

Replace the value below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

Hidden services stay available. 

### Actual Behavior

After some amount of time, usually about 2 days, the hidden services running in DO become inaccessible and the public directory shows no nodes are online, when in truth the directory itself has gone "offline". 

Restarting the process fixes the issue. This seems to only be a problem with the nodes in DO. 

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run the bootstrap nodes in DO
2. Wait a couple days
3. Hidden services are no longer reachable

### LINKED ISSUE #118: Seperate desktop client from orc daemon

### LINKED ISSUE #119: Enforce hashcash stamp on CLAIM

### PR DESCRIPTION
**Pull request by bookchin**
* [x] Upgrade to use v3 tor hidden services (Closes #61, Close #99) 
* [x] Remove/Separate ORC Desktop (Close #118, Close #85, Close #73, Close #74) ((not really close, but move)) 
* [x] Start bridge/api server immediately
* [x] Remove the control port interface
* [x] Require claims have a hashcash stamp (Close #119) 
* [x] Merge directory API with bridge API
* [x] Improved process management
* [x] Remove electron packaging, switch back to shipping with docker
* [x] Expose a stats api from bridge
* [x] Pipe logs to bridge's event controller
* [x] Enforce protocol version stamp compatibility
* [x] Include capacity information in contact map
* [x] More aggressive redundancy/auditing (Close #97) 
* [x] Docker compose mini test-network using chutney
* [x] Improve node discovery/joining
* [x] Test coverage

### CODE REVIEW

**Comment by doodlemania2** [comment]
Is there a new GUI project?

**Comment by bookchin** [comment]
@doodlemania2 not yet, we pulled the GUI out of the base package and are in the process of reworking it. This upgrade had major API changes and we don't want to bind the release cycles for the daemon and GUI together (since different people work on them, and pace is different). We also pulled back from the "easy button" approach for running a provider node for now, since it caused significant churn and stability problems. Going forward, the GUI will likely be a "remote control / dashboard" for a running daemon. We also don't have the time/funds to take on both aspects full time, so my focus right now is on the daemon, API, network, etc. @mrfancymonocle is the lead GUI developer and soon he'll have the GUI that was part of the main ORC package broken out into a standalone package.

**Comment by bookchin** [comment]
Another possible direction we are considering is simply exposing a GUI from the daemon as a regular web application you can access in your browser. 

The electron apps suffered real performance issues. It's a chromium instance for the GUI that spawns another headless chromium instance to run the GUI, which spawns a mongod process and a tor process. The overhead for the two chromium instances alone was enough to warrant ditching electron in my opinion.

**Comment by bookchin** [comment]
What we also found was that the low barrier to entry for running a provider node led to random surges in providers coming online (after a mention on twitter or similar) which were people just trying it out and then turning it off. We don't want ORC nodes on laptops, providers need to understand what they are doing and keep their node online. We are more keen on end user GUI being a thin client.

**Comment by doodlemania2** [comment]
Thank you for the feedback @bookchin ! I agree, this was problematic from a churn perspective - easier to just do Docker anyways.
I think making the client a light client talking to a running daemon is ++ awesome - bonus points if we can get it to talk to a REMOTE daemon (think manage multiple nodes style) but that's a different use case.
Good choice in removing.

**Comment by bookchin** [comment]
Yep, client should be able to control a remote daemon. We'll add a configuration option for exposing the API as an authenticated hidden service and the client will be able to connect to it that way if desired. Will be working with @mrfancymonocle on the UX around that. :relaxed:

**Pull request merged**
